spring:
  application:
    name: spring-boot-admin-client
#  boot:
#    admin:
#      client:
#        url: http://localhost:20000 #注册到 admin server的 url 如果注册到了注册中心就不需要在此配置了，会给adminserver多出重复的应用信息。
management:
  endpoints:
    web:
      exposure:
        include: '*' # 暴露所有端点
  endpoint:
    health:
      show-components: always # 端点监控检查
#logging:
#  file: spring-boot-admin-client.log #日志监控文件
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:10000/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: 30000