spring:
  application:
    name: nacos-ribbon
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.42.16:8848
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include:'*'
