spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: false
server:
  port: 20000
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:10000/eureka
    register-with-eureka: true
    fetch-registry: true