spring:
  application:
    name: openFeign
server:
  port: 11001
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@localhost:10000/eureka/
feign:
  hystrix:
    enabled: true # 开启容错功能
  compression:
    request:
      enabled: false # 是否对请求进行压缩
      mime-types: text/xml,application/xml,application/json # 指定压缩请求类型
      min-request-size: 2048 # 超过此大小时，请求会被压缩
    response:
      enabled: false #是否对响应进行压缩

logging:
  level:
    com.zxf.feign.FeignServiceFeign: debug
