spring:
  application:
    name: config-server-amqp
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zxffe/config.git
          username: zxffe
          password: zxf1063446979
          clone-on-start: true # 启动时直接从git上获取配置
  rabbitmq:
    host: 192.168.137.135
    port: 5672
    username: guest
    password: guest

server:
  port: 12000
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:10000/eureka/
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints: # 暴露bus刷新配置端点
    web:
      exposure:
        include: 'bus-refresh'
  endpoint:
    bus-refresh:
      enabled: true