spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git: #配置存储配置信息的git仓库
          uri: https://gitee.com/zxffe/config.git
          username: zxffe
          password: zxf1063446979
          clone-on-start: true # 开启启动时直接从git获取配置

server:
  port: 12000
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:10000/eureka/
    register-with-eureka: true
    fetch-registry: false

